### ISSUE TITLE
Support styling in description

### ISSUE THREAD

**Issue by turbolay** [Megapont/mega-ui#3]
Descriptions are currently a big chunk of text:

<img width="908" alt="CleanShot 2024-01-14 at 08 28 00@2x" src="https://github.com/Megapont/mega-ui/assets/16029533/e936bc9a-6653-4a98-8f8c-a43cfe175c7c">

It would be better to:
- Ideally, support Markdown
- At least, respect line breaks used while creating the contract

**Comment by mrkmcknz** [comment]
Adding my 2c, I think markdown support would be AMAZING.
