### ISSUE TITLE
Add link on governance panel to token contract

### ISSUE THREAD

**Issue by mrkmcknz** [Megapont/mega-ui#5]
<img width="438" alt="image" src="https://github.com/Megapont/mega-ui/assets/1089376/815e1498-4f09-4169-ab65-0183ee36f3d2">

Would be nice if this link sent the user to the token contract instead of not functioning.

**Comment by Aman-zishan** [comment]
The idea was to have a seperate governance page where community members can add and manage delegates, but it makes sense to have a link to the token for now. 

https://explorer.hiro.so/token/SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.mega?chain=mainnet
